spring.application.name=Ecom-Backend-1
server.port = 8000

spring.datasource.url = jdbc:postgresql://localhost:5432/ecom_db
spring.datasource.username = rohitchaudhury
spring.datasource.password = rohit_postgre

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update